version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python3 app.py
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    depends_on:
      - db

volumes:
  postgres_data:
