version: '3.8'

services:
  bot:
    image: python:3.11-slim  
    container_name: service_bot
    volumes:
      - .:/app  
    working_dir: /app  
    environment:
      - TELEGRAM_TOKEN=${TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    command: >
      sh -c "pip install -r requirements.txt && python app.py"  
